### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by ColinGilbert** [euccastro/gambit-ffi-types#1]
Hi,

I'm sorry for (ab)using Github's issues feature in such a way, but your library has made my day! Thank you so very much for building this tool and generously releasing it under MIT terms! Just know that somewhere, someone is happier thanks to you and your excellent work!

Colin

**Comment by euccastro** [comment]
My pleasure! :)  Let me know if you run into any problems.

You may want to check out @alvatar's www.schemespheres.org, which includes something similar to these struct utilities and a whole lot more.
